SELECT * 
FROM junction_config
WHERE
    id in (?, ?),
    dt in (?, ?), 
    num_lanes INT DEFAULT 1,
    lane_north_straight INT DEFAULT 1,
    lane_south_straight INT DEFAULT 1,
    lane_east_straight INT DEFAULT 1,
    lane_west_straight INT DEFAULT 1,
    lane_north_right INT DEFAULT 0,
    lane_south_right INT DEFAULT 0,
    lane_east_right INT DEFAULT 0,
    lane_west_right INT DEFAULT 0,
    lane_north_left INT DEFAULT 0,
    lane_south_left INT DEFAULT 0,
    lane_east_left INT DEFAULT 0,
    lane_west_left INT DEFAULT 0,
    lane_north_right_straight INT DEFAULT 0,
    lane_south_right_straight INT DEFAULT 0,
    lane_east_right_straight INT DEFAULT 0,
    lane_west_right_straight INT DEFAULT 0,
    lane_north_left_straight INT DEFAULT 0,
    lane_south_left_straight INT DEFAULT 0,
    lane_east_left_straight INT DEFAULT 0,
    lane_west_left_straight INT DEFAULT 0,
    has_left_turn_lane INT DEFAULT 0,
    has_bus_cycle_lane INT DEFAULT 0,
    has_pedestrian_crossing INT DEFAULT 0,
    pedestrian_crossing_duration INT,
    crossing_requests_per_hour INT,
    prioritised_flow TEXT